command:
  - gunicorn
  - app:server
  - --bind
  - 0.0.0.0:8000
  - --workers
  - "2"
  - --timeout
  - "120"
  - --graceful-timeout
  - "30"
env:
  - name: CICD_APP_USE_MOCK
    value: "false"
  - name: AUTH_MODE
    value: "databricks"
  - name: CICD_APP_CATALOG
    value: "demos"
  - name: CICD_APP_SCHEMA
    value: "cicd"
  - name: DATABRICKS_WAREHOUSE_HTTP_PATH
    value: "/sql/1.0/warehouses/e3a0fc2c08db05bb"
  - name: APP_DEBUG
    value: "false"
